### PR TITLE
Travis CI automatic documentation and stack

### PR DESCRIPTION
**Pull request by TravorLZH**
You don't need to worry about doxygen as long as Travis CI is enabled in your repository. In order to set up GH Pages, you need to merge my gh-pages branch to yours.

In #6, you said that:

> I stand corrected. It seems Vector based stack does work better when the data units to be stored is smaller in size, also benefits from caching.

Therefore, why don't you put two stacks in your source code. I hope I really can get write access to your repository because I am currently learning some similar stuff in Jerry Cain's Programming Paradigms lecture

### CODE REVIEW

**Comment by TravorLZH** [comment]
Also, I added `vector` that allows you to do stack operation and `insert` operation.

**Comment by TravorLZH** [comment]
I will be implementing queue in the following commits

**Comment by ParadoxZero** [comment]
Hi, 

There are quite a few reviews I would like to point out, but unfortunately, I am quite busy at the moment ( for a few weeks ).

You work is good, however, you have to understand that I have a design and a plan for the project in my mind which I have been unable to formalize due to lack of time.

As I had mentioned, please refrain from simply sending pull requests with abrupt changes. Make an issue first so that we can discuss it, e.g. - The coding style you used in the commit.

Also regarding the implementation, there are few changes which I would like to suggest. I will get back to it tomorrow.

**Comment by TravorLZH** [comment]
Also, to improve your `make sure it's buildable` requirement. You may use Travis CI to build the Pull Requests, so you can decide whether merge it or not

**Comment by TravorLZH** [comment]
My queue is based on vector, and push add element to the front where pop removes the element at the back. My implementation of `std::queue` is in reverse

**Comment by ParadoxZero** [comment]
I had not approved using the Linux kernel coding style nor using Travis CI. Further, I mentioned earlier, it's too early for API documentation and I am not really looking for using Doxygen.

And please do not send a pull request with an edited readme, where it's content is changed without prior discussion.

**Review by ParadoxZero — CHANGES_REQUESTED** [review]
Except for the follwoing:
* `Vector.h/.c`
* `queue.h/.c`
* `reverse_generic`

Revert everything else.

**Comment by ParadoxZero** [comment]
The reason I have asked to remove your stack implementation is because it is basically replicating the vector code. The `stack` should be an adapter instead of a container.

**Comment by TravorLZH** [comment]
Please discuss in #8

**Pull request closed without merging**
