### PR TITLE
Remove C implementation of VQueue and add macro wrapper

### PR DESCRIPTION
**Pull request by TravorLZH**
Complete #13

### CODE REVIEW

**Comment by ParadoxZero** [comment]
The square root function is not needed as it's already available at `math.h`.

Please remove it.

**Comment by TravorLZH** [comment]
Our library is education purpose, isn't it? Why am I creating a square root function using binary search, because this helps others understand how the square root works

**Comment by ParadoxZero** [comment]
No, this project is not for education. The difficulty of the project is beginner level that's all.

This project is creating a container/algorithm collection that will make it easy to write C programs.

**Comment by TravorLZH** [comment]
OK

**Comment by TravorLZH** [comment]
I basically checkout master to previous commit

**Review by ParadoxZero — APPROVED** [review]

**Pull request merged**
