### PR TITLE
Add swap_generic

### PR DESCRIPTION
**Pull request by TravorLZH**
I add a function called `swap_generic` which helps you swap bytes between two locations.
```c
void swap_generic(void *a,void *b,size_t sz);
```
I also provide `search_generic` which searches bytes matching `key`
```c
void *search_generic(const void *key,const void *base,size_t n,size_t elem_sz);
```
I hope I can gain write access to this repository so that I can contribute it easier

### CODE REVIEW

**Comment by ParadoxZero** [comment]
Hi, thanks for the Pull request.

A suggestion:

- Instead of the swap being inside `generic/` put it inside something like `utils.c` and corresponding `utils.h`. Change the Test correspondingly.

**Review by ParadoxZero — CHANGES_REQUESTED** [review]
Instead of the swap being inside` generic/` put it inside something like `utils.c` and corresponding `utils.h`. Change the Test correspondingly.

**Comment by TravorLZH** [comment]
I have moved the code to `src/utils.h`, and I add a new cool function called `search_generic` which helps you search bytes matching the `key`

**Review by ParadoxZero — APPROVED** [review]
Nice!

**Pull request merged**
