### PR TITLE
Documentation and new_stack

### PR DESCRIPTION
**Pull request by TravorLZH**
In your README, you said that you did not test your stack depending on linked list, so I implemented my new freestanding one, and I add documentation support to your project. Just type `doxygen` to generate fresh HTML documents!

### CODE REVIEW

**Comment by ParadoxZero** [comment]
Implementing a new stack is redundant. 
Not looking for doxygen at the moment. The project is at an extremely early stage. Unnecessary dependency/complication.

Closing the request.

Edit: My idea of documentation is to use the GitHub wiki.

**Comment by TravorLZH** [comment]
Sorry, no offense, but letting stack depending on linked list is somewhat stupid and abstract. You tag this repo `beginner-project` that means it needs to be readable to other beginners, so you should be making the stack simpler.

**Comment by ParadoxZero** [comment]
A stack over a linked list is extremely easy to comprehend, not to mention easy to implement. By itself, there is no DS called stack. In essence, it is built on top of some other DS, like an array, vector or a linked list.  Moreover, comprehension is not the aim of the project.

What you had implemented is basically a form of `vector`.

The correct way forward is to implement a `vector` DS, then something like `v_stack`, which would mean stack using a vector. This removes unnecessary redundancy in the code base.

However, I do not see any reason to use a vector over the linked list for stack after all the complexity of push and pop over stack using linked list is O(1).

From my perspective, having to use `realloc()` when stack size increases put a significant overhead, compared to a linked list. The only gain I see is the reduction of `size_t` memory from each node, which seems like a tradeoff in favor of linked list implementation.

**Comment by ParadoxZero** [comment]
I stand corrected. It seems `Vector` based stack does work better when the data units to be stored is smaller in size, also benefits from caching.

LL works better when storing complex structures due to space saving. Imagine having a Large structure ( e.g. TCB ), and a vector makes a 2x allocation for it.

It seems, the correct way to go is to have two container adaptors for stack - one for LL and one based on vector or something more optimal e.g. `std::dequeue` in STL.

**Comment by TravorLZH** [comment]
Well, my `vector` based stack is actually taken from Jerry Cain's Programming Paradigms Lecture from iTunes U. I suggest you to watch some of the lecture videos because that inspires a lot of generic code

**Pull request closed without merging**
