### PR TITLE
Implement merge sort

### PR DESCRIPTION
**Pull request by TravorLZH**
Merge `master` branch instead

### CODE REVIEW

**Review by ParadoxZero — CHANGES_REQUESTED** [review]
From #11 
Ensure the only files with changes should be:

- `include/genetic/algorithm.h` Here the declaration of mergesort should exist.
- `src/algorithm/mergesort.c` Here the source of mergesort.
- `Test/algorithm/test_mergesort.c` (the name is not important) The test for merge sort.
- `Test/CMakeList.txt` to add algorithms to test suit.
- `Test/algorithm/CMakeList.txt` to add mergesort test to test suit.

Optionally,
- `Readme.md` But the only change should be that mergesort is ticked off.

Clean the branch history and ensure this order. In other words, remove all other changes.

Only then will I be able to merge the request.

**Comment by TravorLZH** [comment]
I don't know how to remove previous commits, so I can only leave them there

**Comment by TravorLZH** [comment]
I have done your request

**Comment by ParadoxZero** [comment]
I can still see a lot of newer commits to master not reflected in your pull request.

**Pull request closed without merging**
